// Copyright (c) 2026 Brad Root
// SPDX-License-Identifier: MPL-2.0

import { describe, it, expect } from 'vitest';
import { searchEmoji, emojiForShortcode } from './emojiData.js';

// emojiData.ts is generated by tools/gen-emoji-data.mjs; these also act as a
// smoke test that the generated table loaded and a regeneration didn't break.

describe('emojiForShortcode', () => {
  it('resolves a known shortcode to its emoji', () => {
    expect(emojiForShortcode('bone')).toBe('🦴');
    expect(emojiForShortcode('+1')).toBe('👍');
  });

  it('is case-insensitive', () => {
    expect(emojiForShortcode('BONE')).toBe('🦴');
  });

  it('returns null for an unknown shortcode', () => {
    expect(emojiForShortcode('definitely_not_an_emoji')).toBeNull();
  });
});

describe('searchEmoji', () => {
  it('ranks an exact shortcode match first', () => {
    expect(searchEmoji('bone')[0]).toEqual({ name: 'bone', emoji: '🦴' });
  });

  it('returns nothing for a query that matches no shortcode', () => {
    expect(searchEmoji('zzzznotreal')).toEqual([]);
  });

  it('caps results at the requested limit', () => {
    expect(searchEmoji('a', 5).length).toBeLessThanOrEqual(5);
  });
});
